version: "3.9"

services:
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=service_db
    networks:
      - spring-postgres
  db:
    image: postgres:15.4
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=service_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
volumes:
  db-data:
networks:
  spring-postgres:
