spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/service_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: true

    # validate db by model
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    enabled: true
    #user: ${FLYWAY_USER}
    #password: ${FLYWAY_PASSWORD}
    baseline-description: "init"
    baseline-version: 0