spring:
  datasource:
    url: jdbc:postgresql://db:5432/service_db
    username: postgres
    password: password

  jpa:
    show-sql: true
    open-in-view: true

    # validate db by model
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    enabled: true
    #user: ${FLYWAY_USER}
    #password: ${FLYWAY_PASSWORD}
    baseline-description: "init"
    baseline-version: 0

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

  api-docs:
    path: /api-docs